#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running lint..."
npm run lint || { echo "Linting failed. Commit aborted."; exit 1; }

echo "Running tests..."
npm run test || { echo "Tests failed. Commit aborted."; exit 1; }
